apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: i2d1o5b0x-go
  janus-idp.io/tekton: i2d1o5b0x-go
  backstage.io/kubernetes-id: i2d1o5b0x-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i2d1o5b0x-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
