apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: i2d1o5b0x-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: i2d1o5b0x-go 
  name: i2d1o5b0x-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: i2d1o5b0x-go 
